/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#9496ff',
        'on-tertiary-fixed-variant': '#5c5e6e',
        'secondary': '#575493',
        'error': '#b41340',
        'tertiary': '#595a6b',
        'error-container': '#f74b6d',
        'on-error-container': '#510017',
        'surface-container-high': '#e6deff',
        'on-surface-variant': '#5e5680',
        'surface-dim': '#d9ceff',
        'primary-fixed': '#9496ff',
        'on-primary': '#f4f1ff',
        'on-secondary': '#f5f1ff',
        'on-secondary-container': '#43407d',
        'surface-container-highest': '#e1d7ff',
        'secondary-fixed-dim': '#c0bdff',
        'error-dim': '#a70138',
        'secondary-dim': '#4b4886',
        'outline': '#7a719d',
        'secondary-container': '#d0cdff',
        'inverse-on-surface': '#a097c5',
        'primary': '#4544dc',
        'on-tertiary-container': '#525464',
        'surface-container': '#ece4ff',
        'on-primary-container': '#0b0081',
        'on-tertiary': '#f3f1ff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#404251',
        'background': '#faf4ff',
        'secondary-fixed': '#d0cdff',
        'on-secondary-fixed-variant': '#4c4987',
        'on-error': '#ffefef',
        'on-background': '#302950',
        'on-primary-fixed': '#000000',
        'on-secondary-fixed': '#2f2c69',
        'surface-container-low': '#f4eeff',
        'tertiary-fixed-dim': '#d8d8ec',
        'tertiary-dim': '#4d4f5f',
        'surface-tint': '#4544dc',
        'outline-variant': '#b1a7d6',
        'primary-dim': '#3735d0',
        'surface-variant': '#e1d7ff',
        'on-surface': '#302950',
        'primary-fixed-dim': '#8486ff',
        'surface-bright': '#faf4ff',
        'inverse-surface': '#0f072e',
        'tertiary-fixed': '#e6e6fa',
        'tertiary-container': '#e6e6fa',
        'surface': '#faf4ff',
        'on-primary-fixed-variant': '#10009c',
        'inverse-primary': '#8183ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Be Vietnam Pro', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
